#!/bin/bash
execute=1

if [ "$1" == "-g" -o "$1" == "-gd" -o "$1" == "-dg" ]
then 
	git add .
	commit_msg=$3
	if [ -z "$3" ]
	then
		echo "Enter a commit message: "
		commit_msg=read
	fi
	git commit -m "$commit_msg"
	git push -u origin master
	script_name="$2"
	if [ "$1" == "-g" ]
	then
		execute=0
	fi
elif [ "$1" == "-d" ]
then 
	script_name="$1"
else
	echo "Usage: deploy <FILENAME> [ARGS]"
	exit
fi

if [ $execute -eq 1 ]
then
	echo "Copying to /usr/local/bin ..."
	sudo cp $script_name/$script_name /usr/local/bin/$script_name
	echo "Done!"
fi
