#!/bin/bash
fullpath="$1"

while [ -d "$fullpath" ]
do
	selection=$(ls $fullpath | rofi -dmenu -p "Search for a file")
	if [ "$selection" == "/b/" ]
	then
		fullpath=$(dirname "$fullpath")
	elif [ "$selection" == "/q/" ]
	then
		exit
	else
		fullpath="$fullpath/$selection"
	fi
done

extension=$(echo $selection | awk -F. '{print $NF}')
echo $extension

if [ $extension == "pdf" ]
then
	choice=$(echo "Open|Copy" | rofi -sep "|" -dmenu -p "$selection")
	if [  $choice == "Open" ]
	then
		firefox "$fullpath"
	else
		xclip -sel clip -target file/pdf -i "$fullpath"
	fi
elif [ $extension == "png" ]
then 
	xclip -sel clip -target image/$extension -i "$fullpath"
else
	echo "We don't do that here"
fi
