#!/bin/bash

selection=$(ls $1 | rofi -dmenu)

fullpath="$1/$selection"

while [ -d "$fullpath" ]
do
	selection=$(ls $fullpath | rofi -dmenu)
	if [ "$selection" == "/b/" ]
	then
		fullpath=$(dirname "$fullpath")
	else
		fullpath="$fullpath/$selection"
	fi
done

extension=$(echo $selection | awk -F. '{print $NF}')
echo $extension

if [ $extension == "pdf" ]
then
	firefox "$fullpath"
elif [ $extension == "png" ]
then 
	xclip -sel clip -target image/$extension -i $fullpath
else
	echo "We don't do that here"
fi
